name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      TODOAPP__DB__URL: ${{ secrets.TODO_TEST_DATABASE_URL }}
      POSTGRES_USER: ${{ secrets.TODO_TEST_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.TODO_TEST_POSTGRES_PASSWORDS }}
      POSTGRES_DB: ${{ secrets.TODO_TEST_POSTGRES_DB }}
    services:
      postgres:
        image: postgres:16.8
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U ${{ env.POSTGRES_USER }}"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install poetry and deps
        run: |
          pip install poetry
          poetry install --with dev
      - name: Run Integration tests
        run: poetry run pytest tests/integration_tests -v
        env:
          TODOAPP__DB__URL: ${{ env.POSTGRES_DB }}
          TODOAPP__DB__ECHO: 0
          TODOAPP__DB__ECHO_POOL: 0
          TODOAPP__DB__MODE: TEST
          TODOAPP__RUN__RELOAD: 1
