name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    container: python:3.12.10
    services:
      postgres:
        image: postgres:16.8
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.TODO_TEST_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TODO_TEST_POSTGRES_PASSWORDS }}
          POSTGRES_DB: ${{ secrets.TODO_TEST_POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry and deps
        run: |
          pip install "poetry==2.1.2"
          poetry install --with dev
      - name: Run integration tests
        run: |
          chmod +x tests/test_prestart.sh
          tests/test_prestart.sh
          poetry run pytest tests/integration_tests -v --junitxml=pytest-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: pytest-results.xml
          reporter: junit
        env:
          TODOAPP__DB__URL: ${{ secrets.TODO_TEST_DATABASE_URL }}
          TODOAPP__DB__ECHO: 0
          TODOAPP__DB__ECHO_POOL: 0
          TODOAPP__DB__MODE: TEST
          TODOAPP__RUN__RELOAD: 1
