name: Lint and typecheck
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.12.10
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          pip install poetry
          poetry install --with dev

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Black checking
        run: poetry run black --check .

      - name: Ruff checking
        run: poetry run ruff check . --output-format=github

      - name: MyPy checking
        run: poetry run mypy . --junit-xml=mypy-report.xml

      - name: Upload test report
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: mypy-report.xml
          require_tests: true
