name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    container: python:3.12.10

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry and deps
        run: |
          pip install poetry
          poetry install --with dev
      - name: Run prestart script
        run: |
          chmod +x ./tests/test_prestart.sh
          ./tests/test_prestart.sh
      - name: Run unit-tests
        run: poetry run pytest tests/unit_tests -v --junitxml=pytest-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: pytest-results.xml
          reporter: junit

