name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    container: python:3.12.10

    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - run: poetry install
      - run: pytest tests/unit_tests -v

